USE [master]
GO

/****** Object:  Database [Humanitarian]    Script Date: 10/18/2015 5:58:33 PM ******/
CREATE DATABASE [Humanitarian]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Humanitarian', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.SQLEXPRESS\MSSQL\DATA\Humanitarian.mdf' , SIZE = 3072KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'Humanitarian_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.SQLEXPRESS\MSSQL\DATA\Humanitarian_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [Humanitarian] SET COMPATIBILITY_LEVEL = 120
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Humanitarian].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Humanitarian] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Humanitarian] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Humanitarian] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Humanitarian] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Humanitarian] SET ARITHABORT OFF 
GO

ALTER DATABASE [Humanitarian] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Humanitarian] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Humanitarian] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Humanitarian] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Humanitarian] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Humanitarian] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Humanitarian] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Humanitarian] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Humanitarian] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Humanitarian] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Humanitarian] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Humanitarian] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Humanitarian] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Humanitarian] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Humanitarian] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Humanitarian] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Humanitarian] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Humanitarian] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [Humanitarian] SET  MULTI_USER 
GO

ALTER DATABASE [Humanitarian] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Humanitarian] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Humanitarian] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Humanitarian] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [Humanitarian] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Humanitarian] SET  READ_WRITE 
GO

